font_family Noto Sans Mono

copy_on_select clipboard

foreground #cdd6f4
background #1e1e2e
background_opacity 0.90

confirm_os_window_close 0

# keep ctrl+shift+f free for nvim/tmux
map ctrl+shift+f no_op
