[tools]
bat = "latest"
bun = "latest"
chezmoi = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
jq = "latest"
neovim = "nightly"
node = "24"
python = "latest"
ripgrep = "latest"
rust = "stable"
uv = "latest"
zoxide = "latest"
