schema_version = 2

[packages.build-essential]

[packages.ca-certificates]

[packages."containerd.io"]

[packages.curl]

[packages.docker-ce]

[packages.docker-ce-cli]

[packages.docker-compose-plugin]

[packages.ffmpeg]

[packages.gh]

[packages.git]

[packages.gnupg]

[packages.lsb-release]

[packages.unzip]

[packages.zsh]
