schema_version = 5

[apt]
present = [
    "build-essential",
    "ca-certificates",
    "containerd.io",
    "curl",
    "docker-ce",
    "docker-ce-cli",
    "docker-compose-plugin",
    "ffmpeg",
    "gh",
    "git",
    "gnupg",
    "imagemagick",
    "lsb-release",
    "openssh-server",
    "tar",
    "unzip",
    "zsh",
]

[yay]
present = [
    "base-devel",
    "ca-certificates",
    "containerd",
    "curl",
    "docker",
    "docker-compose",
    "ffmpeg",
    "git",
    "github-cli",
    "gnupg",
    "imagemagick",
    "lsb-release",
    "openssh",
    "unzip",
    "vi",
    "zellij",
    "zsh",
]
